#' get_looker_token
#'
#' @param client
#' Looker API3 client, obtained by generating a new client using the user administation dashboard in the Looker GUI.
#' This should be stored in an environment variable and NEVER written in your code or shared.
#' @param secret
#' Looker API3 client, obtained by generating a new client using the user administation dashboard in the Looker GUI.
#' This should be stored in an environment variable and NEVER written in your code or shared.
#' @return
#' A character string containing the session token. This can either be passed directly to
#'  \code{run_look()} or stored in an R object to be passed as an argument to \code{run_look()}.
#'  The latter is the preferred method if you are going to be running more than a single look.
#'
#'
#' @export
#'
#' @examples
#'
#' get_looker_token(Sys.getenv("LOOKER_API_3_CLIENT"),
#' Sys.getenv("LOOKER_API_3_SECRET"))
#'
get_looker_token <- function(client, secret){
  looker_token <- httr::POST(paste0("https://upworthy.looker.com:19999/api/3.0/login?client_id=",
                              client,
                              "&client_secret=",
                              secret
  ))
  httr::content(looker_token)$access_token
}



#' run_look
#'
#' @param look_id
#' The ID of a saved look in looker. This is the number at the end of the URL when you open a saved
#' look in the GUI
#' @param token
#' The session token generated by \code{get_session_token}, if NA then a new token is generated
#' @param client
#' Your looker API 3 client, remember to store this in an environment variable
#' @param secret
#' Your looker API 3 client, remember to store this in an environment variable
#' @param base_url
#' The looker URL for your company for Upworthy this is always "https://upworthy.looker.com"
#' @param limit
#' Number of rows to return, will over-ride the settings in the saved look
#' @param cache
#' Whether to return a cached value if available. Generally, you should use the default value
#'
#' @return
#' A dataframe containing the result of running the look.
#'
#' @export
#'
#' @examples
#'
#' # Replace this look id with one you have access to in the GUI.
#'
#' run_look(1969)
#'
#' #Save the token in an intermediary object if running multiple looks
#'
#' token <- get_looker_token(Sys.getenv("LOOKER_API_3_CLIENT"),
#' Sys.getenv("LOOKER_API_3_SECRET"))
#'
#' run_look(1969, token)
#' run_look(1972, token)
#'
run_look <- function(look_id,
                     token = NA,
                     client = Sys.getenv("LOOKER_API_3_CLIENT"),
                     secret = Sys.getenv("LOOKER_API_3_SECRET"),
                     base_url = "https://upworthy.looker.com",
                     limit = 10000,
                     cache = TRUE){
  if(is.na(token)){
    use_token <- get_looker_token(client, secret)
  } else {
    use_token <- token
  }

  url_cache <- ifelse(cache, "true", "false")

  url <- paste0(base_url, ":19999/api/3.0/looks/",
                look_id,
                "/run/json",
                "?limit=", limit,
                "&cache=", url_cache)

  resp <- httr::GET(url,
              httr::add_headers(Authorization = paste0("token ", use_token))
  )

  if( httr::http_type(resp) != "application/json"){
    stop("API did not return json", call. = FALSE)
  }
  out <- jsonlite::fromJSON( httr::content(resp, "text"), simplifyVector = TRUE)
  out
}

